# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I have no idea what I'm doing.
email:
description: > # this means to ignore newlines until "baseurl:"
  Seriously.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shaunplee.github.io" # the base hostname & protocol for your site
twitter_username: s_p_lee
github_username:  shaunplee

# Build settings
markdown: kramdown
#gems: [jekyll-org-mode-converter]
